#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su -
apt-get update && apt-get install -y nginx --fix-missing
# sudo service nginx stop
ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable
# Backup the original index page before overwriting
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak
echo "<html><head></head><body>Hello World!</body></html>" | tee /var/www/html/index.nginx-debian.html > /dev/null
service nginx restart
