#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

# sudo su
apt update && apt install -y nginx
service nginx stop
echo "Hello World!" > /var/www/html/index.html
# cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
service nginx restart
