#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su
# sudo service nginx stop
service nginx stop 
apt-get update && apt-get upgrade
apt-get install -y nginx --fix-missing
apt-get install -y ufw
apt-get autoremove -y && apt-get autoclean -y

ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable
# Backup the original index page before overwriting
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

chown -vR "$USER":"$USER" /var/www/
chown -vR "$USER":"$USER" /etc/nginx

echo "<html><head></head><body>Hello World!</body></html>" > /var/www/html/index.nginx-debian.html
nginx -t && service nginx restart
