#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su -
tee /etc/nginx/snippets/redirect_me.conf > /dev/null <<EOF
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/redirect_me.conf' /etc/nginx/sites-available/default
service nginx restart
