#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su

service nginx stop 
apt-get update && apt-get upgrade
apt-get install -y nginx --fix-missing
apt-get install -y ufw
apt-get autoremove -y && apt-get autoclean -y

ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

tee /etc/nginx/snippets/redirect_me.conf > /dev/null <<EOF
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/redirect_me.conf' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html

chown -vR "$USER":"$USER" /var/www/
chown -vR "$USER":"$USER" /etc/nginx

nginx -t && nginx -s reload
service nginx restart
