#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su

service nginx stop 
apt-get update && apt-get upgrade
apt-get install -y nginx --fix-missing
apt-get install -y ufw
apt-get autoremove -y && apt-get autoclean -y

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

chown -vR "$USER":"$USER" /var/www/
chown -vR "$USER":"$USER" /etc/nginx

tee /etc/nginx/snippets/redirect_me.conf > /dev/null <<EOF
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/redirect_me.conf' /etc/nginx/sites-available/default
echo "<html><head></head><body>Hello World!</body></html>" | tee /var/www/html/index.nginx-debian.html > /dev/null
service nginx restart
