#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su

service nginx stop 
apt-get update && apt-get upgrade
apt-get install -y nginx --fix-missing
apt-get install -y ufw
apt-get autoremove -y && apt-get autoclean -y

ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

chown -vR "$USER":"$USER" /var/www/
chown -vR "$USER":"$USER" /etc/nginx

tee /etc/nginx/snippets/redirect_me.conf > /dev/null <<EOF
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/redirect_me.conf' /etc/nginx/sites-available/default
echo "<html><head></head><body>Hello World!</body></html>" > /var/www/html/index.nginx-debian.html

# create customer 404 page
tee /usr/share/nginx/html/custom_404.html > /dev/null <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>The page you are looking for does not exist.</p>
    <p> Ceci n'est pas une page</p>
</body>
</html>

EOF


tee /etc/nginx/snippets/custom404.conf > /dev/null <<EOF
    error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/custom404.conf' /etc/nginx/sites-available/default
nginx -t && service nginx restart
