#!/usr/bin/env bash
# Bash script that Install nginx on your web-01

sudo su

service nginx stop 
apt-get update && apt-get upgrade
apt-get install -y nginx --fix-missing
apt-get install -y ufw
apt-get autoremove -y && apt-get autoclean -y

ufw allow 22/tcp
ufw allow 80/tcp
ufw --force enable

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen\s*\[::\]:80;/listen [::]:80 default_server;/g' /etc/nginx/sites-available/default

tee /etc/nginx/snippets/redirect_me.conf > /dev/null <<EOF
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/redirect_me.conf' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# create customer 404 page
tee /usr/share/nginx/html/custom_404.html > /dev/null <<EOF
Ceci n'est pas une page

EOF


tee /etc/nginx/snippets/custom404.conf > /dev/null <<EOF
    error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
EOF

sed -i '/^\s*server\s*{/r /etc/nginx/snippets/custom404.conf' /etc/nginx/sites-available/default


chown -vR "$USER":"$USER" /var/www/
chown -vR "$USER":"$USER" /etc/nginx

nginx -t && nginx -s reload
service nginx restart
