#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, using the while loop + IFS
awk 'BEGIN {NF==2} {count[$1 " " $9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
