#!/usr/bin/env bash

sudo ufw --force reset
sudo ufw status
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw --force enable && echo "Firewall is active and enabled on system startup"
