#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.backup
sed -i 's/^127.0.0.2/127.0.0.1 localhost/g' ~/hosts.backup
sed -i 's/^157.240.11.35/8.8.8.8 facebook.com/g' ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts