#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.backup
sed -i 's/127.0.*/127.0.0.1      localhost/' ~/hosts.backup
sed -i 's/157.240.*/8.8.8.8      facebook/' ~/hosts.backup
cp -f ~/hosts.backup /etc/hosts