#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

backup_file="/etc/hosts.backup"
cp /etc/hosts $backup_file
sed -i 's/localhost/127.0.0.1      localhost/' $backup_file
sed -i 's/facebook*/8.8.8.8      facebook.com/' $backup_file
cp -f $backup_file /etc/hosts